# Pipeline de execução no Github Actions.

name: cypress e2e tests

on:

  schedule:
    - cron: '56 20 * * *'
    
  workflow_dispatch:
    inputs:
      RUN_ON_QA:
        description: "Rodar em ambiente QA"
        required: false
        default: false
        type: boolean

      overrideFileRun:
        description: "Execução manual - File to Run (opcional)"
        required: false
        default: ' '
        type: string        
        
permissions:
  checks: write
  contents: read
  
env:
  # Set variables once
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  DASHBOARD_TESTS_RESULT: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  PIPELINE_TEST: "${{ github.workflow }} ${{ github.run_number }}"
  TELEGRAM_POST: "https://api.telegram.org/${{ vars.TELEGRAM_BOT_ID }}/sendMessage"
  TELEGRAM_URL_GROUP: "https://web.telegram.org/k/#${{ vars.TELEGRAM_WEB_URL }}"
  TERM: xterm # evita warning no log no ci do cypress

jobs:
  CypressE2ETests:
    name: "Matrix - Run E2E Cypress Tests"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # cada groupName vai executar os arquivos que respeitem o specPattern
          - groupName: backend
            specPattern: "cypress/e2e/**/*-backend.cy.ts"

          - groupName: frontend
            specPattern: "cypress/e2e/**/*-frontend.cy.ts"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Define Node version"
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: 'Install ts-node globally'
        run: npm install -g ts-node typescript

      - name: 'Install npm dependencies'
        run: npm install --force

      - name: Cache npm packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: 'Install npm dependencies'
        run: npm ci --prefer-offline

      - name: 'Cypress verify'
        run: npm run cy:verify
        
      - name: 'Validate notify'
        shell: bash
        run: |
          if [[ "${{ vars.NOTIFY }}" == "true" && -z "${{ vars.NOTIFY_ON }}" ]]; then
            echo "[ERRO] Variável de onde notificar deve ser informada"
            echo "vars.NOTIFY_ON = '${{ vars.NOTIFY_ON }}'"
            exit 1
          fi

      - name: 'Debug - Print Variables'
        run: |
          echo "⚙️ Debug variables ⚙️"
          
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "GITHUB_RUN_NUMBER = $GITHUB_RUN_NUMBER"
          echo "Trigger disparada a partir da branch: $GITHUB_REF"
          echo "Reason: $GITHUB_EVENT_NAME"
          echo "SourceBranchName: $GITHUB_REF_NAME"
          echo "NOTIFY = ${{ vars.NOTIFY }}"
          echo "NOTIFY_ON = ${{ vars.NOTIFY_ON }}"
          echo "NOTIFY_ON_SUCCESS = ${{ vars.NOTIFY_ON_SUCCESS }}"
          echo "NOTIFY_ERR_TELEGRAM_SCHEENSHOT = ${{ vars.NOTIFY_ERR_TELEGRAM_SCHEENSHOT }}"
          echo "NOTIFY_ERR_TELEGRAM_VIDEO = ${{ vars.NOTIFY_ERR_TELEGRAM_VIDEO }}"
          echo "github.run_id: ${{ github.run_id }}"
          echo "github.run_number: ${{ github.run_number }}"
          echo "groupName: ${{ matrix.groupName }}"
          echo "Node Version: "
          node -v
          echo "specPattern: ${{ matrix.specPattern }}"
          echo "overrideFileRun: ${{ github.event.inputs.overrideFileRun }}"

      # por motivos de boas práticas deve ser definido uma baseUrl para o cypress,
      # por padrão o da master por isso apenas o qa deve ser trocado a baseUrl e url da api
      - name: 'QA - Cypress E2E tests'
        if: ${{ github.event.inputs.RUN_ON_QA == 'true' }}
        env:
          CYPRESS_BASE_URL_API: ${{ vars.BASE_URL_API }}
          CYPRESS_BASE_URL_QA: ${{ vars.BASE_URL_QA }}

          CYPRESS_SEU_BARRIGA_USERNAME: ${{ vars.SEU_BARRIGA_USERNAME }}
          CYPRESS_SEU_BARRIGA_EMAIL: ${{ vars.SEU_BARRIGA_EMAIL }}
          CYPRESS_SEU_BARRIGA_PASSWD: ${{ secrets.SEU_BARRIGA_PASSWD }}

          CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}
          CYPRESS_NOTIFY: ${{ vars.NOTIFY }}
          CYPRESS_NOTIFY_ON: ${{ vars.NOTIFY_ON }}
          CYPRESS_NOTIFY_ON_SUCCESS: ${{ vars.NOTIFY_ON_SUCCESS }}

          CYPRESS_NOTIFY_ERR_TELEGRAM_SCHEENSHOT: ${{ vars.NOTIFY_ERR_TELEGRAM_SCHEENSHOT }}
          CYPRESS_NOTIFY_ERR_TELEGRAM_VIDEO: ${{ vars.NOTIFY_ERR_TELEGRAM_VIDEO }}
          CYPRESS_TELEGRAM_BOT_ID: ${{ vars.TELEGRAM_BOT_ID }}
          CYPRESS_TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}

          CYPRESS_AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

        run: |
          echo "🔥🚀 QA - Executando testes..."
          echo "O baseUrl será configurado para usar o valor: ${{ vars.BASE_URL_QA }}"

          npx cypress run \
            --spec "${{ matrix.specPattern }}" \
            --config baseUrl=${{ vars.BASE_URL_QA }} \
            --headless
      # --browser chrome \

      - name: 'Master - Cypress E2E tests'
        if: ${{ github.event.inputs.RUN_ON_QA != 'true' }}
        env:
          CYPRESS_BASE_URL_API: ${{ vars.BASE_URL_API }}
          CYPRESS_BASE_URL_QA: ${{ vars.BASE_URL_QA }}

          CYPRESS_SEU_BARRIGA_USERNAME: ${{ vars.SEU_BARRIGA_USERNAME }}
          CYPRESS_SEU_BARRIGA_EMAIL: ${{ vars.SEU_BARRIGA_EMAIL }}
          CYPRESS_SEU_BARRIGA_PASSWD: ${{ secrets.SEU_BARRIGA_PASSWD }}

          CYPRESS_RECORD_KEY: ${{ secrets.RECORD_KEY }}
          CYPRESS_NOTIFY: ${{ vars.NOTIFY }}
          CYPRESS_NOTIFY_ON: ${{ vars.NOTIFY_ON }}
          CYPRESS_NOTIFY_ON_SUCCESS: ${{ vars.NOTIFY_ON_SUCCESS }}

          CYPRESS_NOTIFY_ERR_TELEGRAM_SCHEENSHOT: ${{ vars.NOTIFY_ERR_TELEGRAM_SCHEENSHOT }}
          CYPRESS_NOTIFY_ERR_TELEGRAM_VIDEO: ${{ vars.NOTIFY_ERR_TELEGRAM_VIDEO }}
          CYPRESS_TELEGRAM_BOT_ID: ${{ vars.TELEGRAM_BOT_ID }}
          CYPRESS_TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}

          CYPRESS_AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}

        run: |
          echo "🔥🚀 Master Executando testes..."

          npx cypress run \
            --spec "${{ matrix.specPattern }}" \
            --headless
      
      - name: 'Generate documentation.md'
        if: ${{ vars.PUBLISH_DOC && github.ref == 'refs/heads/master' }}
        run: |
          echo "🛠️ Gerando documentação markdown, para publicação posterior"
          ts-node cypress/scripts/generate-md.ts

      # npx cypress run --record --key $(CYPRESS_RECORD_KEY) --parallel --ci-build-id $BUILD_BUILDNUMBER --env... # run on cypress cloud

      # Publica o resultados de todos os testes, de todas as matrices -  É possível publicar separado os relatórios com o $(groupName)
      - name: 'Publish Tests results'
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'cypress/results/**.xml'
          fail_on_failure: true
          require_tests: true
          include_passed: true
          detailed_summary: true

      # pública o arquivo after_run-results.json, gerado no cypress, no cypress.config.ts > 'after:run'
      - name: "Publica after_run-results.json"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: afterRunResults
          path: cypress/fixtures/geral/tmp/monitoramento/after_run-results.json



      # Da part de publicação de documentação, será comentada aqui, porque esse arquivo é para execução no github, não no azure. 
      # Teria que configurar o envio da documentação, nesse caso, para o repositório específico do cliente.

      # O processo de documentação pode ser ignorado, mudando a variable PUBLISH_DOC da library
      #
      # Processo:
      # Encontra os testes de api, gerador pela task saveApiDoc();
      # Publica a documentação, organizados conforme definido no path do saveApiDoc().
      # - name: "Wiki Documentation"  
      #   if: false && vars.PUBLISH_DOC && matrix.groupName == 'backend'
      #   run: |
      #     echo "📚 Publicando documentação na Wiki do Azure, gerada em teste anterior..."

  NotifyTestSuccessResults:
    name: "Successo - Notificação"
    runs-on: ubuntu-latest
    needs: CypressE2ETests
    if: success() && vars.NOTIFY == 'true' && vars.NOTIFY_ON_SUCCESS == 'true'

    steps:
      - name: "Baixa after_run-results.json"
        uses: actions/download-artifact@v4
        with:
          name: afterRunResults
          path: ./afterRunResults

      - name: "Telegram"
        if: vars.NOTIFY_ON == 'TELEGRAM'
        env:
          TELEGRAM_BOT_ID: ${{ vars.TELEGRAM_BOT_ID }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
        run: |
          echo "👉 Notificará sucesso..."

          # Valida variáveis required para o fluxo
          if [ -z "$TELEGRAM_BOT_ID" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            # -z = variável vazia ou não definida
            echo "❌ ERRO = Variáveis obrigatórias não informadas!"
            echo "TELEGRAM_BOT_ID=$TELEGRAM_BOT_ID"
            echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID"
            exit 1
          fi

          echo "⚙️ Debug variables ⚙️"

          echo "TELEGRAM_CHAT_ID = $TELEGRAM_CHAT_ID"
          echo "TELEGRAM_BOT_ID = $TELEGRAM_BOT_ID"
          echo "TELEGRAM_POST = $TELEGRAM_POST"
          echo "DASHBOARD_TESTS_RESULT = $DASHBOARD_TESTS_RESULT"

          # extrai variáveis
          CY_RESULTS_FILE_PATH="./afterRunResults/after_run-results.json"

          if [ ! -s "$CY_RESULTS_FILE_PATH" ]; then
            echo "❌ Arquivo $CY_RESULTS_FILE_PATH não encontrado ou vazio!"
            ls -lah "$(dirname "$CY_RESULTS_FILE_PATH")"
            exit 1
          fi

          # itera sobre o results.json e atribui valor às variáveis
          for key in $(jq -r 'keys[]' "$CY_RESULTS_FILE_PATH"); do
            value=$(jq -r --arg k "$key" '.[$k]' "$CY_RESULTS_FILE_PATH")

            if [ "$key" = "baseUrl" ]; then
              baseUrl="$value"
            elif [ "$key" = "base_url_api" ]; then
              base_url_api="$value"
            elif [ "$key" = "endedTestsAt" ]; then
              endedTestsAt="$value"
            elif [ "$key" = "totalDuration" ]; then
              totalDuration="$value"
            elif [ "$key" = "totalPassed" ]; then
              totalPassed="$value"
            elif [ "$key" = "totalFailed" ]; then
              totalFailed="$value"
            elif [ "$key" = "totalSuites" ]; then
              totalSuites="$value"
            elif [ "$key" = "totalTests" ]; then
              totalTests="$value"
            elif [ "$key" = "osName" ]; then
              osName="$value"
            elif [ "$key" = "cypressVersion" ]; then
              cypressVersion="$value"
            elif [ "$key" = "browserName" ]; then
              browserName="$value"
            elif [ "$key" = "browserVersion" ]; then
              browserVersion="$value"
            fi
          done

          echo "⚙️ Debug variables ⚙️"

          echo "baseUrl = $baseUrl"
          echo "base_url_api = $base_url_api"
          echo "endedTestsAt = $endedTestsAt"
          echo "totalDuration = $totalDuration"
          echo "totalPassed = $totalPassed"
          echo "totalFailed = $totalFailed"
          echo "totalSuites = $totalSuites"
          echo "totalTests = $totalTests"
          echo "osName = $osName"
          echo "cypressVersion = $cypressVersion"
          echo "browserName = $browserName"
          echo "browserVersion = $browserVersion"

          echo "🚀 Enviando mensagem..."

          payloadSuccess=$(cat <<EOF
          {
            "chat_id": "$TELEGRAM_CHAT_ID",
            "parse_mode": "HTML",
            "text": "✅ <b>Testes executados com sucesso!</b>\n
            ━━━━━━━━━━━━━━━━━━━\n
            🧪 <b>Framework:</b> Cypress $cypressVersion\n
            🖥️ <b>Navegador:</b> $browserName - $browserVersion\n
            🌐 <b>Servidor:</b> $baseUrl\n
            📡 <b>API:</b> ${base_url_api:-N/A}\n
            🔁 <b>Pipeline:</b> ${{ github.workflow }} ${{ github.run_number }}\n
            📊 <b>Testes executados:</b> $totalSuites Suites - $totalTests Testes\n
            📅 <b>Executado em:</b> $endedTestsAt\n
            📈 <a href=\"$DASHBOARD_TESTS_RESULT\">Results Dashboard</a>"
          }
          EOF
          )
          
          response=$(curl -s -w "\n%{http_code}" -X POST "$TELEGRAM_POST" \
            -H "Content-Type: application/json" \
            -d "$payloadSuccess"
          )

          responseBody=$(echo "$response" | sed '$d')
          status_code=$(echo "$response" | tail -n1)

          echo "Status Code: $status_code"

          if [ "$status_code" -ne 200 ]; then
            echo "❌ Erro ao enviar mensagem para o Teams"
            echo "Response body:"
            echo "$responseBody"
            exit 1
          else
            echo "✅ Mensagem enviada com sucesso!"
          fi

      - name: "Teams"
        if: vars.NOTIFY_ON == 'TEAMS'
        env:
          TEAMS_URL: ${{ vars.TEAMS_URL }}
        run: |
          echo "Notificando sucesso..."

          echo "TEAMS_URL = $TEAMS_URL"
          echo "DASHBOARD_TESTS_RESULT = $DASHBOARD_TESTS_RESULT"

          # extrai variáveis
          CY_RESULTS_FILE_PATH="./afterRunResults/after_run-results.json"

          if [ ! -s "$CY_RESULTS_FILE_PATH" ]; then
            echo "Arquivo $CY_RESULTS_FILE_PATH não encontrado ou vazio!"
            ls -lah "$(dirname "$CY_RESULTS_FILE_PATH")"
            exit 1
          fi

          # itera sobre o results.json e atribui valor às variáveis
          for key in $(jq -r 'keys[]' "$CY_RESULTS_FILE_PATH"); do
            value=$(jq -r --arg k "$key" '.[$k]' "$CY_RESULTS_FILE_PATH")

            if [ "$key" = "baseUrl" ]; then
              baseUrl="$value"
            elif [ "$key" = "base_url_api" ]; then
              base_url_api="$value"
            elif [ "$key" = "endedTestsAt" ]; then
              endedTestsAt="$value"
            elif [ "$key" = "totalDuration" ]; then
              totalDuration="$value"
            elif [ "$key" = "totalPassed" ]; then
              totalPassed="$value"
            elif [ "$key" = "totalFailed" ]; then
              totalFailed="$value"
            elif [ "$key" = "totalSuites" ]; then
              totalSuites="$value"
            elif [ "$key" = "totalTests" ]; then
              totalTests="$value"
            elif [ "$key" = "osName" ]; then
              osName="$value"
            elif [ "$key" = "cypressVersion" ]; then
              cypressVersion="$value"
            elif [ "$key" = "browserName" ]; then
              browserName="$value"
            elif [ "$key" = "browserVersion" ]; then
              browserVersion="$value"
            fi
          done

          echo "⚙️ Debug variables ⚙️"

          echo "baseUrl = $baseUrl"
          echo "base_url_api = ${base_url_api:-N/A}"
          echo "endedTestsAt = $endedTestsAt"
          echo "totalDuration = $totalDuration"
          echo "totalPassed = $totalPassed"
          echo "totalFailed = $totalFailed"
          echo "totalSuites = $totalSuites"
          echo "totalTests = $totalTests"
          echo "osName = $osName"
          echo "cypressVersion = $cypressVersion"
          echo "browserName = $browserName"
          echo "browserVersion = $browserVersion"

          # <<EOF -heredoc, uma forma de escrever blocos de texto multilinha no shell
          # Tudo que estiver entre <<EOF e EOF(pode ser qualquer palavra) será considerado texto literal
          status_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$TEAMS_URL" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "type": "AdaptiveCard",
            "\$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "version": "1.2",
                  "msteams": { "width": "Full" },
                  "body": [
                    {
                      "type": "ColumnSet",
                      "columns": [
                        {
                          "type": "Column",
                          "width": "stretch",
                          "items": [
                            {
                              "type": "TextBlock",
                              "text": " ✅ A execução dos testes E2E foi finalizado com Sucesso",
                              "wrap": true,
                              "spacing": "Small"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        { "title": "🧪 Framework:", "value": "Cypress $cypressVersion" },
                        { "title": "🖥️ Navegador", "value": "$browserName - $browserVersion" },
                        { "title": "🌐 Servidor:", "value": "$baseUrl" },
                        { "title": "📡 API:", "value": "$base_url_api" },
                        { "title": "🔁 Pipeline:", "value": "${{ github.workflow }} ${{ github.run_number }}" },
                        { "title": "📊 Testes Executados:", "value": "$totalSuites Suites - $totalTests Testes" },
                        { "title": "📅 Executado em:", "value": "$endedTestsAt" },
                        { "title": "🕒 Tempo de Execução:", "value": "$totalDuration" }
                      ]
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "📈 Results Dashboard",
                      "url": "$DASHBOARD_TESTS_RESULT"
                    }
                  ]
                }
              }
            ]
          }
          EOF
          )

          APPEND_STT_RESPONSE_CODE="- Status code esperado = 202, Status code retornado $status_code"

          if [ "$status_code" -ne 202 ]; then
            echo "Erro no envio de mensagem $APPEND_STT_RESPONSE_CODE"
            exit 1
          else
            echo "Mensagem enviada com sucesso $APPEND_STT_RESPONSE_CODE"
          fi

  NotifyTestFailResults:
    name: "Falha - Notificação"
    runs-on: ubuntu-latest
    needs: CypressE2ETests
    if: failure() && vars.NOTIFY

    steps:
      - name: "Baixa after_run-results.json"
        uses: actions/download-artifact@v4
        with:
          name: afterRunResults
          path: ./afterRunResults

      - name: "Telegram"
        if: vars.NOTIFY_ON == 'TELEGRAM'
        env:
          TELEGRAM_BOT_ID: ${{ vars.TELEGRAM_BOT_ID }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
        run: |
          echo "👉 Notificará erro..."

          # Valida variáveis required para o fluxo
          if [ -z "$TELEGRAM_BOT_ID" ] || [ -z "$TELEGRAM_CHAT_ID" ]; then
            # -z = variável vazia ou não definida
            echo "❌ ERRO = Variáveis obrigatórias não informadas!"
            echo "TELEGRAM_BOT_ID=$TELEGRAM_BOT_ID"
            echo "TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID"
            exit 1
          fi

          echo "⚙️ Debug variables ⚙️"

          echo "TELEGRAM_CHAT_ID = $TELEGRAM_CHAT_ID"
          echo "TELEGRAM_BOT_ID = $TELEGRAM_BOT_ID"
          echo "TELEGRAM_POST = $TELEGRAM_POST"
          echo "DASHBOARD_TESTS_RESULT = $DASHBOARD_TESTS_RESULT"

          # extrai variáveis
          CY_RESULTS_FILE_PATH="./afterRunResults/after_run-results.json"

          if [ ! -s "$CY_RESULTS_FILE_PATH" ]; then
            echo "❌ Arquivo $CY_RESULTS_FILE_PATH não encontrado ou vazio!"
            ls -lah "$(dirname "$CY_RESULTS_FILE_PATH")"
            exit 1
          fi

          echo "⚙️ Conteúdo do arquivo ⚙️"
          cat "$CY_RESULTS_FILE_PATH" | jq

          # itera sobre o results.json e atribui valor às variáveis
          for key in $(jq -r 'keys[]' "$CY_RESULTS_FILE_PATH"); do
            value=$(jq -r --arg k "$key" '.[$k]' "$CY_RESULTS_FILE_PATH")

            if [ "$key" = "baseUrl" ]; then
              baseUrl="$value"
            elif [ "$key" = "base_url_api" ]; then
              base_url_api="$value"
            elif [ "$key" = "endedTestsAt" ]; then
              endedTestsAt="$value"
            elif [ "$key" = "totalDuration" ]; then
              totalDuration="$value"
            elif [ "$key" = "totalPassed" ]; then
              totalPassed="$value"
            elif [ "$key" = "totalFailed" ]; then
              totalFailed="$value"
            elif [ "$key" = "totalSuites" ]; then
              totalSuites="$value"
            elif [ "$key" = "totalTests" ]; then
              totalTests="$value"
            elif [ "$key" = "osName" ]; then
              osName="$value"
            elif [ "$key" = "cypressVersion" ]; then
              cypressVersion="$value"
            elif [ "$key" = "browserName" ]; then
              browserName="$value"
            elif [ "$key" = "browserVersion" ]; then
              browserVersion="$value"
            fi
          done

          echo "⚙️ Debug variables ⚙️"

          echo "baseUrl = $baseUrl"
          echo "base_url_api = $base_url_api"
          echo "endedTestsAt = $endedTestsAt"
          echo "totalDuration = $totalDuration"
          echo "totalPassed = $totalPassed"
          echo "totalFailed = $totalFailed"
          echo "totalSuites = $totalSuites"
          echo "totalTests = $totalTests"
          echo "osName = $osName"
          echo "cypressVersion = $cypressVersion"
          echo "browserName = $browserName"
          echo "browserVersion = $browserVersion"

          echo "🚀 Enviando mensagem..."

          payloadFail=$(cat <<EOF
          {
            "chat_id": "$TELEGRAM_CHAT_ID",
            "parse_mode": "HTML",
            "text": "❌ <b>Atenção: Testes executados com erros!</b>\n
            ━━━━━━━━━━━━━━━━━━━\n
            📅 <b>Executado em:</b> $endedTestsAt\n
            🧪 <b>Framework:</b> Cypress $cypressVersion\n
            🖥️ <b>Navegador:</b> $browserName - $browserVersion\n
            🌐 <b>Servidor:</b> $baseUrl\n
            📡 <b>API:</b> ${base_url_api:-N/A}\n
            🔁 <b>Pipeline:</b> ${{ github.workflow }} ${{ github.run_number }}\n
            📊 <b>Testes executados:</b> $totalSuites Suites - $totalTests Testes\n
            🟢 <b>Testes com sucesso:</b> '"$totalPassed"'\
            🔴 <b>Testes com erro:</b> '"$totalFailed"'\
            📈 <a href=\"$DASHBOARD_TESTS_RESULT\">Results Dashboard</a>"
          }
          EOF
          )

          echo "payloadFail = $payloadFail"
          echo "payloadFail = $(payloadFail)"
          
          response=$(curl -s -w "\n%{http_code}" -X POST "$TELEGRAM_POST" \
            -H "Content-Type: application/json" \
            -d "$(payloadFail)"
          )

          responseBody=$(echo "$response" | sed '$d')
          status_code=$(echo "$response" | tail -n1)

          echo "Status Code: $status_code"

          if [ "$status_code" -ne 200 ]; then
            echo "❌ Erro ao enviar mensagem para o Teams"
            echo "Response body:"
            echo "$responseBody"
            exit 1
          else
            echo "✅ Mensagem enviada com sucesso!"
          fi
    
